title: Pawan Pandey - Full Stack Developer
email: Pawan4email@gmail.com
description: >-
  Senior .NET Full Stack Developer with 11+ years of experience in designing,
  developing, and deploying enterprise-grade web applications.
baseurl: ""
url: "https://ppandey33.github.io"
github_username: ppandey33
linkedin_username: pawan-pandey-48842a79

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor